language: python
# Ensure travis provides Python 3.5
python: 3.5
install:
  # virtualenv>=14.0.0 has dropped python 3.2 support
  - pip install "virtualenv<14.0.0" tox
script:
  - tox
env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
